### ISSUE TITLE
Thanks For your sharing. But some questions about Align the reference alleles across datasets

### ISSUE THREAD

**Issue by TrumanZYX** [agkatzionis/Sepsis-MR#1]
We found the coding about align the reference alleles across datasets, which means means that the effect allele of exposure is equal to the effect allele of outcome. But this is incomplete because there are also effector alleles that are equal but other genes that are not equal, like following picture.(https://mrcieu.github.io/TwoSampleMR/articles/harmonise.html)
![image](https://user-images.githubusercontent.com/55921297/201467069-291733d1-c0d0-470d-b909-28252baf9c72.png)

sepsis.hunt.bmi2 <- sepsis.hunt.bmi
for (i in 1:nrow(bmi2)) {
  if (as.character(sepsis.hunt.bmi$EA[i]) != as.character(bmi2$bmi_ea[i])) {
    sepsis.hunt.bmi2$Beta[i] <- - sepsis.hunt.bmi$Beta[i]
    sepsis.hunt.bmi2$EA[i] <- sepsis.hunt.bmi$OA[i]
    sepsis.hunt.bmi2$OA[i] <- sepsis.hunt.bmi$EA[i]
    sepsis.hunt.bmi2$EAF[i] <- 1 - sepsis.hunt.bmi$EAF[i]
  }
}

**Comment by agkatzionis** [comment]
Hi, thank you for your comment. You are right, we did not properly account for palindromic SNPs in this. I have rerun the analyses excluding all palindromic SNPs and have added the two updated .R files ("Sepsis MR - No Palindromic SNPs.R" and "Covid MR - No Palindromic SNPs.R") to this repository. I have included them as separate files and not as edits, so that the original files can still reproduce the analyses included in the printed version of our paper. Thankfully, removing palindromic SNPs had very little impact on our results.
